version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-smartwaste}
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 4000
      MONGO_URI: mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASSWORD:-example}@mongo:27017/${MONGO_DB_NAME:-smartwaste}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-change-me}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_TTL_MS: ${JWT_REFRESH_TTL_MS:-2592000000}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000,http://localhost:19006}
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    depends_on:
      - mongo
  web:
    build:
      context: ./web-frontend
      args:
        REACT_APP_API_URL: ${WEB_REACT_APP_API_URL:-http://localhost:4000}
    environment:
      REACT_APP_API_URL: ${WEB_REACT_APP_API_URL:-http://localhost:4000}
    ports:
      - "${WEB_PORT:-3000}:80"
    depends_on:
      - backend
volumes:
  mongo-data: